version: "3.8"
services:
  backend1 :
    build: ./backend/
    ports:
    - "1111:8000"
  backend2 :
    build: ./backend/
    ports:
    - "2222:8000"
  backend3 :
    build: ./backend/
    ports:
    - "3333:8000"
  database:
    build: ./database/
    ports:
    - "5432:5432"
  loadbalancer:
    build: ./loadbalancer/
    ports:
    - "8080:80"
    depends_on:
    - backend1
    - backend2
    - backend3
