# Stage 1: Create the Nginx container
FROM nginx:alpine

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf
# COPY nginxL4.conf /etc/nginx/nginx.conf

# Expose port 80 (default for Nginx)
EXPOSE 80
